### ISSUE TITLE
Device returns a state without value

### ISSUE THREAD

**Issue by vlebourl** [iMicknl/python-tahoma-api#28]
Somfy Thermostat can return the following states that crashes [line 139](https://github.com/iMicknl/python-tahoma-api/blob/e00b472ac772701bc1573ff5f9c05ab177bb5498/pyhoma/models.py#L139) of models.py:

```yaml
{'deviceStates': [{'name': 'core:BatteryLevelState',
                    'type': 2,
                    'value': '83.0'},
                   {'name': 'core:DerogationActivationState',
                    'type': 3,
                    'value': 'inactive'},
                   {'name': 'core:DerogatedTargetTemperatureState',
                    'type': 2,
                    'value': '16.0'},
                   {'name': 'somfythermostat:DerogationHeatingModeState',
                    'type': 3,
                    'value': 'manualMode'},
                   {'name': 'somfythermostat:DerogationTypeState',
                    'type': 3,
                    'value': 'further_notice'},
                   {'name': 'core:DerogationStartDateTimeState',
                    'type': 5,
                    'value': '1596438624000'},
                   {'name': 'core:DerogationEndDateTimeState', 'type': 0}],    <<====================
  'deviceURL': 'somfythermostat://SOMFY_THERMOSTAT-2479/xxx#1',
  'name': 'DeviceStateChangedEvent',
  'setupOID': 'xxx',
  'timestamp': 1596438652475},
```
